version: 1.0.{build}

# https://www.appveyor.com/docs/macos-images-software/#operating-system

image: macos-sonoma # 2C6G120G
# image: macos-ventura # 2C6G120G

matrix:
  fast_finish: true

environment:
  LANG: C.UTF-8
  LC_ALL: C.UTF-8

init:
  - appveyor version
  - sw_vers
  - uname -a
  - sysctl -n machdep.cpu.brand_string
  - system_profiler SPHardwareDataType
  - df -h
  - sysctl -n hw.ncpu
  - sysctl -n hw.physicalcpu
  - sysctl -n hw.logicalcpu
  - sysctl -n hw.memsize
  - printenv | sort
  - ls -1 /Applications | grep -i Xcode
build_script:
  - echo 123
on_success:
on_failure:
on_finish:
