name: "Print Runner Info"
description: "print Runner Info"
runs:
  using: "composite"
  steps:
    - name: Print Runner Info
      shell: bash
      run: |
        set -euxo pipefail
        uname -a || true
        system_profiler SPSoftwareDataType SPHardwareDataType SPMemoryDataType SPStorageDataType || true
        sysctl machdep.cpu.brand_string hw.memsize || true
        free -h || true
        df -h || true
        lscpu || true
        sw_vers || true
        sysctl hw.physicalcpu hw.logicalcpu || true
        wmic cpu get NumberOfCores,NumberOfLogicalProcessors || true
        uptime || true
        sysctl -n vm.loadavg || true
        top -l 1 | head -10 || true
        memory_pressure || true
        vm_stat || true
        ps -eo %cpu,comm | sort -nr | head -10 || true
        systeminfo || true
        printenv | sort
