name: "Remote Desktop"
description: "remote desktop"

inputs:
  password:
    description: "password"
    required: false
    default: "P@ssw0rd123!"

runs:
  using: "composite"
  steps:
    - name: Remote Desktop
      shell: bash
      run: |
        set -euxo pipefail
        cd "${{ github.action_path }}"

        echo "$RUNNER_OS"
        echo "${{ inputs.password }}"

        chmod +x *.sh
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          ./macos_vnc.sh ${{ inputs.password }}
        fi
