# https://docs.github.com/en/actions/reference/runners/github-hosted-runners
# https://github.com/marketplace?type=actions

name: Debug
on:
  # push:
  workflow_dispatch:

jobs:
  debug:
    # runs-on: macos-15-intel # x86_64 4C14G109G
    # runs-on: macos-26-intel # x86_64 4C14G151G
    runs-on: macos-latest # arm64 3C7G44G
    # runs-on: macos-15 # arm64 3C7G44G
    steps:
      - uses: actions/checkout@v6

      - name: Run Info
        shell: bash
        run: |
          set -euxo pipefail
          uname -a || true
          system_profiler SPHardwareDataType || true
          sysctl machdep.cpu.brand_string || true
          free -h || true
          df -h || true
          lscpu || true
          sw_vers || true
          sysctl hw.physicalcpu hw.logicalcpu || true
          wmic cpu get NumberOfCores,NumberOfLogicalProcessors || true
          uptime || true
          sysctl -n vm.loadavg || true
          top -l 1 | head -10 || true
          memory_pressure || true
          vm_stat || true
          ps -eo %cpu,comm | sort -nr | head -10 || true
          systeminfo || true
          printenv | sort

      # - uses: fawazahmed0/action-debug-vscode@main # touch continue
