# https://docs.github.com/en/actions/reference/runners/github-hosted-runners
# https://github.com/marketplace?type=actions

name: Debug Mac
on:
  # push:
  workflow_dispatch:

jobs:
  debug_mac:
    # 实际上arm机比intel机性能更高更稳定
    runs-on: macos-15-intel # Macmini6,2 i7-8700B x86_64 4C14G109G
    # runs-on: macos-26-intel # Macmini6,2 i7-8700B x86_64 4C14G151G
    # runs-on: macos-latest # VirtualMac2,1 M1 arm64 3C7G44G
    # runs-on: macos-15 # VirtualMac2,1 M1 arm64 3C7G44G
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/print_runner_info

      # - uses: ./.github/actions/remote_desktop
      #   env:
      #     NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      #     SSH_KEY: ${{ secrets.SSH_KEY }}
      #     SSH_IP: ${{ secrets.SSH_IP }}
      #     SSH_PORT: ${{ secrets.SSH_PORT }}

      # - uses: docker/setup-docker-action@v5 # 7min
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      # - uses: docker/setup-qemu-action@v4
      # - uses: docker/setup-buildx-action@v4
      # - uses: docker/login-action@v4
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - uses: fawazahmed0/action-debug-vscode@main # touch continue


      # - uses: owenthereal/action-upterm@v1 # touch continue
      #   if: failure()
