# https://docs.github.com/en/actions/reference/runners/github-hosted-runners
# https://github.com/marketplace?type=actions

name: Debug
on:
  # push:
  workflow_dispatch:

jobs:
  debug:
    # runs-on: macos-15-intel # x86_64 4C14G109G
    # runs-on: macos-26-intel # x86_64 4C14G151G
    runs-on: macos-latest # arm64 3C7G44G
    # runs-on: macos-15 # arm64 3C7G44G
    steps:
      - uses: actions/checkout@v4

      - name: Run Info
        shell: bash
        run: |
          sw_vers
          uname -a
          sysctl machdep.cpu.brand_string
          system_profiler SPHardwareDataType
          df -h
          printenv | sort
          ls -1 /Applications | grep -i Xcode

      - uses: fawazahmed0/action-debug-vscode@main # touch continue
