name: Dispatch Remote
on:
  repository_dispatch:
    types: [dispatch_remote]

jobs:
  dispatch_remote:
    runs-on: ${{ github.event.client_payload.build.runner }}
    permissions: write-all
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.client_payload.repo.name }}
          ref: ${{ github.event.client_payload.repo.sha }}
          token: ${{ secrets.PAT }} # Settings-Developer Settings-Personal access tokens (classic)
          lfs: true
          fetch-depth: 1

      - name: Replace Action
        shell: bash
        run: |
          set -euxo pipefail
          export DYNAMIC_ACTION=./.github/actions/dynamic_action
          rm -rf $DYNAMIC_ACTION
          mkdir -p $DYNAMIC_ACTION
          cp -rf ${{ github.event.client_payload.build.action }} $DYNAMIC_ACTION
      - name: Dynamic Action
        uses: ./.github/actions/dynamic_action
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      # - name: Dispatch Remote
      #   shell: bash
      #   run: |
      #     set -euxo pipefail
      #     gh workflow run ${{ github.event.client_payload.build.action }} --repo Alost/actions
      #   env:
      #     GH_TOKEN: ${{ secrets.PAT }}
