name: Dispatch Build
on:
  repository_dispatch:
    types: [dispatch_build]

jobs:
  dispatch_build:
    runs-on: ${{ github.event.client_payload.build.runner }}
    permissions: write-all
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.client_payload.repo.name }}
          ref: ${{ github.event.client_payload.repo.sha }}
          token: ${{ secrets.PAT }} # Settings-Developer Settings-Personal access tokens (classic)
          lfs: true
          fetch-depth: 1

      - uses: ./.github/actions/print_runner_info

      - uses: ./.github/actions/free_disk_space
        if: ${{ github.event.client_payload.build.free_disk_space }}

      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ github.event.client_payload.name }}
          cache-on-failure: "true"
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      # - uses: mxschmitt/action-tmate@v3
      #   if: ${{ github.event.client_payload.build.debug }}
      #   with:
      #     detached: true
      #     timeout-minutes: 5
      - uses: fawazahmed0/action-debug-vscode@main # touch continue
        if: ${{ github.event.client_payload.build.debug }}

      - name: Run Script
        shell: bash
        run: ${{ github.event.client_payload.build.script }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ github.event.client_payload.artifact.enable }}
        with:
          name: ${{ github.event.client_payload.artifact.name }}
          path: ${{ github.event.client_payload.artifact.path }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        # Settings -> Actions -> General -> Workflow permissions -> Read and write permissions
        if: ${{ github.event.client_payload.release.enable }}
        with:
          tag_name: ${{ github.event.client_payload.release.tag_name }}
          name: ${{ github.event.client_payload.release.name }}
          body: ${{ github.event.client_payload.release.body }}
          files: ${{ github.event.client_payload.release.files }}
          draft: false
          prerelease: false

      # - uses: mxschmitt/action-tmate@v3
      #   if: ${{ github.event.client_payload.build.end_debug }}
      #   with:
      #     detached: true
      #     timeout-minutes: 5
      - uses: fawazahmed0/action-debug-vscode@main # touch continue
        if: ${{ github.event.client_payload.build.end_debug }}

      - uses: dawidd6/action-send-mail@v11
        if: failure()
        with:
          server_address: ${{ secrets.SMTP_SERVER_ADDRESS }}
          server_port: ${{ secrets.SMTP_SERVER_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.SMTP_USERNAME }}
          to: ${{ secrets.SMTP_TO }}
          subject: Github Actions ${{ github.event.client_payload.name }} Build Failed
          body: |
            ${{ job.status }}
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      # - uses: mxschmitt/action-tmate@v3
      #   if: failure()
      #   timeout-minutes: 2
      - uses: fawazahmed0/action-debug-vscode@main # touch continue
        if: ${{ failure() && github.event.client_payload.build.fail_debug }}
