name: Dispatch Remote
on:
  repository_dispatch:
    types: [dispatch_remote]

jobs:
  dispatch_build:
    runs-on: ${{ github.event.client_payload.build.runner }}
    permissions: write-all
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.client_payload.repo.name }}
          ref: ${{ github.event.client_payload.repo.ref }}
          sha: ${{ github.event.client_payload.repo.sha }}
          token: ${{ secrets.PAT }} # Settings-Developer Settings-Personal access tokens (classic)
          lfs: true
          fetch-depth: 1
      # - uses: ./.github/actions/dispatch_remote
      #   with:
      #     action: ${{ github.event.client_payload.build.action }}
      - name: Dispatch Remote
        shell: bash
        run: |
          gh workflow run ${{ github.event.client_payload.build.action }}
        env:
          GH_TOKEN: ${{ github.token }}
